from __future__ import annotations

TILE_SIZE = 16

MAP_TILE_WIDTH = 10
MAP_TILE_HEIGHT = 8
HUD_TILE_HEIGHT = 2

SCREEN_TILE_WIDTH = 10
SCREEN_TILE_HEIGHT = 10

SCREEN_WIDTH = SCREEN_TILE_WIDTH * TILE_SIZE
SCREEN_HEIGHT = SCREEN_TILE_HEIGHT * TILE_SIZE

MAP_PIXEL_WIDTH = MAP_TILE_WIDTH * TILE_SIZE
MAP_PIXEL_HEIGHT = MAP_TILE_HEIGHT * TILE_SIZE
HUD_PIXEL_HEIGHT = HUD_TILE_HEIGHT * TILE_SIZE
HUD_PIXEL_Y = MAP_PIXEL_HEIGHT

INTERNAL_WIDTH = SCREEN_WIDTH
INTERNAL_HEIGHT = SCREEN_HEIGHT
MAP_WIDTH_TILES = MAP_TILE_WIDTH
MAP_HEIGHT_TILES = MAP_TILE_HEIGHT
WINDOW_SCALE = 4
SCALE_FACTOR = WINDOW_SCALE
WINDOW_WIDTH = SCREEN_WIDTH * WINDOW_SCALE
WINDOW_HEIGHT = SCREEN_HEIGHT * WINDOW_SCALE

GRID_WIDTH = MAP_TILE_WIDTH
GRID_HEIGHT = MAP_TILE_HEIGHT

ENTITY_SIZE_PX = TILE_SIZE
PLAYER_SIZE_PX = TILE_SIZE
MONSTER_SIZE_PX = TILE_SIZE

PLAYER_SPEED_PX_PER_STEP = 2.0
MONSTER_SPEED_RATIO = 0.5
MONSTER_SPEED_PX_PER_STEP = PLAYER_SPEED_PX_PER_STEP * MONSTER_SPEED_RATIO

PLAYER_HP_DEFAULT = 5
PLAYER_GOLD_DEFAULT = 0
PLAYER_KEYS_DEFAULT = 0

TARGET_FPS = 60

MONSTER_HIT_KNOCKBACK_PX = TILE_SIZE
MONSTER_STUN_TICKS = TARGET_FPS

ACTION_NOOP = 0
ACTION_UP = 1
ACTION_DOWN = 2
ACTION_LEFT = 3
ACTION_RIGHT = 4
ACTION_A = 5
ACTION_B = 6

ACTION_LABELS = {
    ACTION_NOOP: "WAIT",
    ACTION_UP: "UP",
    ACTION_DOWN: "DOWN",
    ACTION_LEFT: "LEFT",
    ACTION_RIGHT: "RIGHT",
    ACTION_A: "INTERACT",
    ACTION_B: "SHIELD",
}

DIRECTION_VECTORS = {
    "up": (0.0, -1.0),
    "down": (0.0, 1.0),
    "left": (-1.0, 0.0),
    "right": (1.0, 0.0),
}

MOVE_ACTION_TO_DIRECTION = {
    ACTION_UP: "up",
    ACTION_DOWN: "down",
    ACTION_LEFT: "left",
    ACTION_RIGHT: "right",
}

ITEM_NAME_TO_ID = {
    "empty": 0,
    "sword": 1,
    "shield": 2,
    "key": 3,
    "potion": 4,
}

COLOR_FRAME_BG = (14, 18, 20)
COLOR_MAP_BG = (24, 34, 32)
COLOR_MAP_GRID = (42, 58, 55)
COLOR_WALL = (76, 96, 92)
COLOR_PLAYER = (248, 234, 120)
COLOR_CHEST = (192, 126, 54)
COLOR_CHEST_OPEN = (110, 160, 92)
COLOR_NPC = (98, 176, 220)
COLOR_MONSTER_CHASER = (214, 86, 86)
COLOR_MONSTER_AMBUSHER = (236, 140, 74)
COLOR_MONSTER_PATROLLER = (176, 118, 214)
COLOR_TRAP = (210, 92, 120)
COLOR_BUTTON = (100, 180, 110)
COLOR_EXIT_NORMAL = (116, 188, 170)
COLOR_EXIT_LOCKED = (146, 118, 72)
COLOR_EXIT_CONDITIONAL = (118, 130, 198)
COLOR_HUD_BG = (12, 14, 18)
COLOR_HUD_PANEL = (24, 28, 34)
COLOR_HUD_ACCENT = (88, 164, 148)
COLOR_HUD_TEXT = (232, 236, 238)
COLOR_HUD_TEXT_DIM = (162, 172, 176)

MESSAGE_DEFAULT = "EXPLORE"
